theme = "adwaita-dark"

[editor]
true-color = true
line-number = "relative"
indent-guides.render = true
rulers = [80]
text-width = 80
soft-wrap.enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

