theme = "dracula_at_night"

[editor]
true-color = true
line-number = "relative"
indent-guides.render = true
rulers = [80]
text-width = 80
soft-wrap.enable = true
auto-save=true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

# AI Assistant Integration (Auggie)
[keys.normal.space.a]
i = ":sh ~/.local/bin/auggie-session continue"      # Continue current session (default)
n = ":sh ~/.local/bin/auggie-session new"           # Start fresh conversation thread
r = ":sh ~/.local/bin/auggie-session refactor"      # Quick refactor current selection/function
t = ":sh ~/.local/bin/auggie-session test"          # Generate tests for current code
f = ":sh ~/.local/bin/auggie-session fix"           # Fix issues in current selection
q = ":sh ~/.local/bin/auggie-session quality"       # Run quality checks (sanitizers, etc.)
"?" = ":sh echo 'Auggie commands: i=continue, n=new, r=refactor, t=test, f=fix, q=quality'"        # Show command reference
w = ":sh ~/.local/bin/auggie-session agreement"     # Open working agreement
