[language-server.gpt]
command = "helix-gpt"

[language-server.ts]
command = "typescript-language-server"
args = ["--stdio"]
language-id = "javascript"

[[language]]
name = "cpp"
language-servers = [
    "clangd",
    "gpt"
]

[linter]
command = "clang-tidy"
args = ["--quiet"]

[formatter]
command = "clang-format"
args = ["--style=file"]

[[language]]
name = "rust"
language-servers = [
    "rust-analyzer",
    "gpt"
]

[[language]]
name = "typescript"
language-servers = [
    "ts",
    "gpt"
]

[[language]]
name = "zig"
language-servers = [
    "zig",
    "gpt"
]

